import { Metadata } from 'next'
import '../globals.css'
import { Poppins } from 'next/font/google'
import PortalTemplate from './template/PortalTemplate'
import Providers from '@/context'

export const metadata: Metadata = {
  title: 'KenPoly',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '300', '400', '600', '700', '800', '900'],
})

const PortalLayout = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-slate-50`}>
        <Providers>
          <PortalTemplate>{children}</PortalTemplate>
        </Providers>
      </body>
    </html>
  )
}

export default PortalLayout
