import { Metadata } from "next";
import "../globals.css";
import { Poppins } from "next/font/google";
import PortalTemplate from "./template/PortalTemplate";
import { getSession } from "next-auth/react";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "KenPoly",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "600", "700", "800", "900"],
});

const PortalLayout = async ({
  children,
}: Readonly<{ children: React.ReactNode }>) => {
  const session = await getSession();

  if (!session) {
    redirect("/");
  }
  return (
    <html lang="en">
      <body className={`${poppins.className} bg-slate-50`}>
        <PortalTemplate>{children}</PortalTemplate>
      </body>
    </html>
  );
};

export default PortalLayout;
